Nexmo/deved-platform

- components/Tag.vue
* #netlify
* #vuejs
* #reactjs
* #community
* **What kind of change does this PR introduce?**
Adding new blog tags
> Added 4 new tags

- bin/exporter
Change import script to only import files that havent already been created
> Change import script to only import NEW files

- lang/en-US.js
- lang/it.js
- lang/zh-CN.js
- layouts/default.vue
- nuxt.config.js
Now shows the message in console in the language selected on the web page
> Lang Changes 

- lang/nl.js
Added Dutch translations for the file in` lang/`.
> nl.js add Dutch translation

- pages/authors/_author.vue
- pages/authors/index.vue
- pages/blog/_year/_month/_day/_slug.vue
- pages/blog/_year/_month/_day/index.vue
- pages/blog/_year/_month/index.vue
- pages/blog/_year/index.vue
- pages/blog/index.vue
- pages/blog/p/_page.vue
Fixes #164 by using the translate function from context correctly
> bug: problem accessing translate function from wrong context

- lang/bs-Cyrl.js
- lang/bs-Latn.js
- lang/en-US.js
Added Bosnian translations in Latin and Cyrillic, and fixed a typo in the English file.
> Bosnian translation in Latin and Cyrillic

- lang/sv.js
Fixing a mistake I made in this pull https://github.com/Nexmo/deved-platform/pull/174
There should not have been a space before ellipses.
> Fixed spaces.

- pages/blog/_slug.vue
- pages/blog/_year/_month/_day/_slug.vue
> Fixes #180 - conditional include of spotlight banner on slug

- content/categories.json
> Shift brand yellow up the pantone chart to be web safe and accessible

- components/Tags.vue
> Fix tag group height so no tags doesnt effect other components

- components/Card.vue
- components/CardFeatured.vue
> Add external link icon if the post has a redirect

- static/admin/config.yml
> Update text hint for tags field in Netlify CMS

- static/admin/config.yml
- static/admin/index.html
- static/admin/netlify-preview.css
Edit to `/static/admin/index.html` to introduce new preview config and stylesheet, and new file `/static/admin/netlify-preview.css`
No previews
Adds preview to Netlify CMS
No
None
> Add previews into Netlify CMS

- static/search.xml
> add search.xml file

- components/DemoBar.vue
- layouts/default.vue
- nuxt.config.js
> fixes 326 - add button to preview deploys to go straight to post

- components/Tag.vue
- components/global/BackToTop.vue
- components/global/TagTester.vue
> fixes #223 and #224 tag issues and backtotop

- components/Tag.vue
- modules/config.js
- pages/tags/_tag/index.vue
> fix: fixes #238 move map to site config and use map from config in tag query AND tag component

- content/authors/laka.json
The current 96px size is too small for the author page, and you know how vain I can be 😘 
Bug Fix
Pixelated author image on the author page
Better quality image
Don't think so.
> Increase the size for Gravatar

- components/Authors/AuthorBubble.vue
- components/Authors/AuthorCard.vue
- components/Authors/AuthorPage.vue
- plugins/filters.js
> fix: handle missing author image

- pages/authors/_author.vue
> fix: add authors name to breadcrumb title

- components/Header.vue
> feat: add vonage.com link in header

- pages/categories/_category/index.vue
> fix: error using object rather than object property for category name

- assets/css/main.css
- components/SocialSharing.vue
- nuxt.config.js
- package-lock.json
- package.json
- pages/blog/_year/_month/_day/_slug.vue
- tailwind.config.js
> feat: add social network sharing buttons to blog aside

- content/blog/en/sms-spam-detection-with-machine-learning-in-python.md
> fix: external links being made relative because they're enclosed in quotes

- CHANGELOG.md
- _redirects
- assets/css/main.css
- components/BackToTop.vue
- components/Header.vue
- components/RelatedPosts.vue
- components/SocialSharing.vue
- components/TableOfContents.vue
- components/Twitch.vue
- content/blog/en/sms-spam-detection-with-machine-learning-in-python.md
- netlify.toml
- nuxt.config.js
- package-lock.json
- package.json
- pages/authors/_author.vue
- pages/blog/_year/_month/_day/_slug.vue
- pages/categories/_category/index.vue
- static/googledd87c7542bc7fce5.html
- tailwind.config.js
**Please check if the PR fulfills these requirements**
**What is the new behavior (if this is a feature change)?**
* exclude certain urls from sitemaps ([107fb79](https://github.com/Nexmo/deved-platform/commit/107fb79c7c57ddbcdd2f2ea3c678f043ffb13b3e))
* remove errant backtick from the end of the Vonage.com link ([9284ae4](https://github.com/Nexmo/deved-platform/commit/9284ae4d2d87cbfabb02718e6baf836cc63d1ecc))
* add google verification file ([cf071c4](https://github.com/Nexmo/deved-platform/commit/cf071c4f3c352f8cb6257497cdb85ee1a81298f9))
* twitch test code removed ([a095f8e](https://github.com/Nexmo/deved-platform/commit/a095f8e2ae8e6e00f70aab14b7f23240439a73e3))
* add authors name to breadcrumb title ([#436](https://github.com/Nexmo/deved-platform/issues/436)) …
> chore: release 2.2.2 (2020-11-25)

- components/Authors/AuthorCard.vue
- components/Authors/AuthorPage.vue
- pages/authors/_author.vue
- pages/blog/_year/_month/_day/_slug.vue
Visual improvements
- The author card crops the author image, which isn't required now that it's in it's own column
- The blog post tiles utilise all three columns, but this looks odd
## Blog Post
- The author card crops the image
- The blog post image is cropped top-and-bottom
- Author image is no longer cropped
- Three layouts depending on viewport width
- Created a smaller vertical layout for the author card when at the smallest viewport
- Blog image no longer crops
> Updates to Author Page & Card

- content/blog/en/how-to-build-a-learning-platform-using-vonage-javascript-typescript-react-express-and-apollo-graphql.md
> fix: image urls never changed for uploaded images

- modules/config.js
- static/search.xml
> fix: xml and rss issues

- components/Breadcrumbs.vue
- components/Footer.vue
- nuxt.config.js
> fix: nuxt trailing slashes enabled

- netlify-plugins/algolia-export/index.js
> fix: clear algolia index before adding records to it

- static/search.xml
> fix: opensearch url still wrong

- components/HeroSearch.vue
> fix: search path updates for trailingSlash changes

- static/admin/config.yml
> fix: prevent em/en dash in titles and subsequently slugs

- CHANGELOG.md
- assets/css/main.css
- package-lock.json
- package.json
> fix: add styling to inline code

- components/CardSearch.vue
> fix: add trailing where none exists for search

- lang/en-US.js
Removing mention of the free credit being able to get you a number.
Text only change
N/A
> Update Sign Up Number Text for <sign-up number> component

- components/CardSearch.vue
> fix(search): links not getting trailing slashes

- static/admin/config.yml
> fix: authors not having identifier for saving

- content/authors/michaeljolley.json
> Updating author profile for MJ

- pages/spotlight/index.vue
* **Please check if the PR fulfils these requirements**
- You've followed the [contributing guidelines][contributing]
- You've adhered to the [code of conduct][coc]
Spotlight submission form update
* **What is the current behaviour?** (You can also link to an open issue here)
Outdated content
* **What is the new behaviour (if this is a feature change)?**
Updated content according to new Spotlight process
No
> Spotlight form update

- content/categories.json
-  You've followed the [contributing guidelines][contributing]
-  You've adhered the [code of conduct][coc]
Add Startup Category
> Add Startup Category

- pages/blog/_year/_month/_day/_slug.vue
> Add "Last updated on MMM D, YYYY" for blog posts

- netlify.toml
Fix
Links to `/blog/tag/technology`
Redirects to `/tags/technology-api`
No
> Add tag redirects

- pages/spotlight/index.vue
Updates
Form accepts a link
Form accepts pasted-in draft
No
> Edits to dev spotlight submission form

- content/blog/en/video-express-is-here-and-why-it’s-awesome.md
* **What kind of change does this PR introduce?** Workaround, can't edit tags via the CMS
* **What is the current behavior?** Tagged `express` instead of `video-express`
* **What is the new behavior (if this is a feature change)?** Tag corrected
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?) It shouldn't, but the error in Netlify when trying to update the post suggests there may be automation that won't be done. Hopefully any of that will be caught on the next build just due to the metadata changing.
> Changed video-express tag
